brew "bash-completion"
brew "bash-git-prompt"
brew "colordiff"
brew "fzf"
brew "go"
brew "jq"
brew "ncdu"
brew "neovim"
brew "pinentry-mac"
brew "the_silver_searcher"
brew "tmux"
brew "watch"
brew "wget"

cask "font-droid-sans-mono-for-powerline"
